>TA15405 |||hypothetical protein|Theileria annulata|chr 02|||Manual
METKKKFSSPTALAVSPPKLTFHRRIARGAFGVVYLVSDDTGTQFAVKRSKKLLFHKQSI
IYLVIYHLSCSLVLPFYSLVT
>TA20245 |||hypothetical protein|Theileria annulata|chr 01|||Manual
MVFKIKELGYLLKPGEKFTNEEDCIDDININTKSEIYLINSKSNLINQFLFLILFLILII
TKIEEKLNEMELKLNDKNWIETLTIIGNTIPQNNNLTLNQQFNELANEFIKIGLNNFKVI
>TA14160 |||hypothetical protein|Theileria annulata|chr 02|||Manual
MSCGSFVAGIVQGILTSAKFVSNHIYLNYLYSYLLEGGLNTSSRVKQHPLP
