module ApiLocUmbrellaLocalisationMappings
  APILOC_UMBRELLA_LOCALISATION_MAPPINGS = {
    'apicoplast' => [
      'apicoplast',
      'apicoplast intermembrane space',
      'apicoplast lumen',
      'apicoplast membrane',
      'apicoplast periphery',
      'innermost apicoplast membrane',
    #      'near apicoplast membranes', # the only example of this ferrochelatase, which isn't apicoplast.
      'outermost apicoplast membrane',
      'nowhere except apicoplast'
    ],
    
    'apical' => [
      'anterior cytoplasm',
      'anterior structure','anterior vacuole',
      'anterior vesicle','apical',
      'apical annuli',
      'apical conoid',
      'apical end of endoplasmic reticulum',
      'apical end of surface',
      'apical end of the nuclear envelope',
      'apical most tip',
      'apical parasite plasma membrane',
      'cap at basal end of daughter',
      'cap at basal end of mother',
      'conoid',
      'conoid collar',
      'conoid fiber ends',
      'cytoplasmic face of the host plasma membrane at moving junction',
      'dense granule',
      'electron dense collar',
      'extracellular apical pole of ookinete protrusion',
      'high electron dense microneme',
      'limiting membrane of rhoptry',
      'luminal membrane of rhoptry',
      'microdomains of dense granule membrane',
      'microneme',
      'microneme lumen',
      'microneme membrane',
      'mononeme',
      'nascent conoid',
      'nascent rhoptry',
      'nowhere except rhoptry',
      'nowhere except apical',
      'nowhere except microneme',
      'pellicle',
      'pellicle membrane',
      'peripheral of microneme',
      'rhoptry',
      'rhoptry body',
      'rhoptry bulb',
      'rhoptry neck',
      'spherical body organelle',
      'sub-apical',
      'sub-pellicular region at the anterior',
    
    # merged merozoite surface locs below
    #      'merozoite surface' => [
      'merozoite surface',
      'apical plasma membrane',
      'apical surface',
      'around merozoite',
      'merozoite surface',
    #      ],
    
    ],
    
    'inner membrane complex' => [
      'attachment site of subpellicular microtubule',
      'beneath alveoli',
      'cytoplasmic face of inner membrane complex',
      'daughter inner membrane complex',
      'free end of inner membrane complex',
      'inner membrane complex',
      'inner membrane complex microtubules',
      'mother inner membrane complex',
      'moving junction',
      'ring at basal end',
      'ring structure at apical inner membrane complex',
      'ring structure at posterior inner membrane complex',
      'nowhere except cytoplasmic face of inner membrane complex',
    
    
    ],
    
    
    'endoplasmic reticulum' => [
      'cortical endoplasmic reticulum',
      'endoplasmic reticulum',
      'endoplasmic reticulum associated vesicle',
      'perinuclear endoplasmic reticulum',
    
    
    ],
    
    
    'golgi apparatus' => [
      'cis-golgi',
      'cisternal rims of the late golgi',
      'cytoplasmic region close to the golgi',
      'golgi',
      'golgi apparatus',
      'golgi associated transport vesicle',
      'golgi matrix',
      'post golgi compartment',
      'trans golgi',
      'trans-golgi network',
    
    
    
    
    ],
    
    
    'exported' => [
      'cleft like parasitophorous vacuole membrane protrusion',
      'close to parasitophorous vacuole membrane',
      'cytoplasmic face of host erythrocyte membrane',
      'cytoplasmic inclusion',
      'cytoplasmic matrix',
      'cytoplasmic side of erythrocyte membrane',
      'cytoplasmic side of host cell membrane',
      'cytosolic face of plasma membrane',
      'cytosolic side of host cell membrane',
      'erythrocyte',
      'erythrocyte cytoplasm',
      'erythrocyte cytoplasm adjacent to the parasitophorous vacuole',
      'erythrocyte cytoplasmic structure',
      'erythrocyte cytoplasmic structure near parasitophorous vacuole',
      'erythrocyte cytoplasmic vesicle',
      'erythrocyte cytosol',
      'erythrocyte periphery',
      'erythrocyte plasma membrane',
      'exoneme',
      'exported',
      'exposed erythrocyte plasma membrane',
      'gametocyte attached erythrocytic vesicle',
      'hepatocyte cytoplasm',
      'host cell',
      'host cell cytoplasm',
      'host cell cytosol',
      'host cell membrane',
      'host cell nucleus',
      'host cell plasma membrane',
      'host cell surface',
      'host erythrocyte membrane',
      'intraerythrocytic cysternae',
      'knob',
      'maurer\'s cleft',
      'maurer\'s cleft tethers',
      'membrane of lysed erythrocyte',
      'single small vesicle in erythrocyte',
      'vesicle under erythrocyte surface',
      'dot like structures in host cell',
    
    ],
    
    'parasite plasma membrane' => [
      'cyst wall',
      'nowhere except parasite plasma membrane',
      'nowhere except sporozoite plasma membrane',
      'nowhere except sporozoite surface',
      'ookinete surface',
      'outer membrane of cyst wall',
      'parasite plasma membrane',
      'plasma membrane',
      'plasma membrane surounding oocyst cytoplasm',
      'proximal to plasma membrane',
      'sporozoite surface',
      'straight side of d shaped parasite',
      'surface',
      'surrounding parasite',
      'under parasite plasma membrane',
      'underneath plasma membrane',
      'vesicle near parasite surface',
      'vesicle-like structure just under the parasite membrane',
      'vesicles near parasite surface',
    ],
    
    
    'cytoplasm' => [
      'cytoplasm',
      'cytoplasm proximal to amylopectin-like granules',
      'cytoplasmic accumulation',
      'cytoplasmic foci',
      'cytosol',
      'intracellular',
      'intracellular inclusion',
      'merozoite cytosol',
      'peripheral',
      'periphery of parasite',
      'throughout parasite',
    ],
    
    
    'nucleus' => [
      'far nuclear periphery',
      'interior of nucleus',
      'mitotic spindle in nucleus',
      'nowhere except nucleus',
      'nuclear',
      'nuclear envelope',
      'nuclear interior',
      'nuclear membrane',
      'nuclear pole',
      'nucleolus',
      'nucleus',
      'outer nuclear envelope',
      'replication foci',
      'replication foci in nucleus',
      'telomeric cluster',
      'perinuclear',
      'histones',
      'nuclear matrix',
      'perhiphery of nucleus',
    ],
    
    
    'food vacuole' => [
      'food vacuole',
      'food vacuole lumen',
      'food vacuole membrane',
    
    ],
    
    
    'mitochondrion' => [
      'inner membrane space side of inner membrane of mitochondria',
      'matrix side of mitochondrial inner membrane',
      'mitochondria',
      'mitochondrial inner membrane',
      'mitochondrial inner membrane space',
      'mitochondrial matrix',
      'mitochondrial membrane',
      'mitochondrial outer membrane',
      'mitochondrion',

    ],
    
    'parasitophorous vacuole' => [
      'only parasitophorous vacuole membrane',
      'parasitophorous vacuole',
      'parasitophorous vacuole close to food vacuole',
      'parasitophorous vacuole membrane',
      'parasitophorous vacuole subdomains',
      'periphery of parasitophorous vacuole',
      'punctate parasitophorous vacuole',
      'sporozoite parasitophorous vacuole 1',
      'tubular structure in parasitophorous vacuole',
      'distal end of parasitophorous vacuole',
      'parasitophorous vacuole lumen',
      'membranous parasitophorous vacuole tubules',
    ],
    
    'other' => [
    'acidocalcisome',
'acrosome',
'adjacent to mitochondrion',
'adjacent to the inner membrane complex',
'anterior adjacent to mitochondria',
'anterior adjacent to mitochondrion',
'anterior to nucleus',
'area around nucleus',
'area near nucleus',
'around cytomeres',
'basal',
'basal complex',
'basal of nucleus',
'between endoplasmic reticulum and golgi',
'between pellicle and parasitophorous vacuole membrane',
'beyond erythrocyte membrane',
'cell poles',
'cell surface',
'centriole',
'centrocone',
'centrosome',
'cone shaped body of basal complex',
'crystalloid',
'crystalloid body',
'cyst matrix',
'cytoplasmic structure',
'cytoplasmic vesicle',
'cytoskeleton',
'cytostome',
'dense band',
'developing cyst wall',
'early endosome',
'electron-dense heterochromatic region at the nuclear periphery',
'endosomal membrane',
'endosomal vacuole',
'endosome-related compartment',
'evacuole',
'exflagellation centre',
'extracellular',
'feeder organelle',
'flagellar basal bodies',
'flagellate basal body',
'food vacuole region',
'gliding trail',
'host tissue',
'individual merozoites inside merozomes',
'inner membrane space side of inner membrane of mitochondria',
'inner surface of peripheral vacuoles',
'internal membrane networks',
'internal organelle',
'internal structures',
'intracellular vacuole',
'intracellular vacuole membrane',
'intravacuolar network',
'intravacuolar tubular network',
'invasion furrow',
'lysosome',
'membrane structure',
'merozoite associated material',
'microtubule',
'multi-lamellar vesicle',
'multi-vesicular endosome',
'near apicoplast membranes',
'non-invasion-related localisation',
'oocyst capsule',
'oocyst protrusion',
'oocyst wall',
'ookinete apical surface',
'ookinete protrusion',
'osmiophilic body',
'p-body',
'peripheral of oocyst protrusion',
'periphery',
'periphery of amylopectin-like granules',
'peroxisome',
'posterior',
'posterior cytoplasm',
'posterior extremity of cup-shaped inner membrane cytoskeleton scaffolds',
'posterior structure',
'posterior to nucleus',
'posterior vacuole',
'posterior vesicle',
'prerhoptry',
'released into extracellular mileiu',
'residual body',
'residual body membrane',
'reticular staining outside apicoplast',
'secretory organelle',
'spindle pole',
'spread around parasite',
'subcapsular areas',
'subpellicular microtubule',
'surrounding',
'trail',
'transformation bulb',
'transport vesicle',
'tubulovesicular membrane',
'two unknown vesicular bodies',
'vac',
'vacuole',
'vesicle',
'vesicle budding off zoite posterior',
'vesicles',
'wall forming body',
'wall forming body type ii',
'zygote remnant',
'zygote side',
    ]
  }
end
