class DevelopmentalStageTopLevelDevelopmentalStages < ActiveRecord::Base
  APILOC_DEVELOPMENTAL_STAGE_TOP_LEVEL_DEVELOPMENTAL_STAGES = {
    'unclassified' => [
      'intraerythrocytic'
    ],
    'ring' => [
      'early intraerythrocytic',
      'ring',
      'early ring',
      'late ring',
    ],
    'trophozoite' => [

    ],
    'schizont' => [
      'late intraerythrocytic',
    ]
    
  }

  KNOWN_DEVELOPMENTAL_STAGES = {
    Species::FALCIPARUM_NAME => [
      'intraerythrocytic',
      'early intraerythrocytic',
      'late intraerythrocytic',
      'ring',
      'early ring',
      'late ring',
      'trophozoite',
      'early trophozoite',
      'middle schizont',
      'late trophozoite',
      'late trophozoite or early schizont',
      'late trophozoite or schizont',
      'after trophozoite',
      'schizont',
      'early schizont',
      'late schizont',
      'segmenter',
      'segmenting schizonts',
      'rupturing schizont',
      'merozoite',
      'after parasitophorous vacuole membrane breakdown',
      'after microneme exocytosis',
      'gametocytogenesis',
      'gametocyte',
      'gametocyte stage I',
      'gametocyte stage II',
      'gametocyte stage III',
      'gametocyte stage IV',
      'gametocyte stage V',
      'gametocyte stage III-V',
      'male gametocyte stage I',
      'male gametocyte stage II',
      'male gametocyte stage III',
      'male gametocyte stage IV',
      'male gametocyte stage V',
      'exflagellating male gametocyte',
      'female gametocyte stage I',
      'female gametocyte stage II',
      'female gametocyte stage III',
      'female gametocyte stage IV',
      'female gametocyte stage V',
      'developing gametocyte',
      'gametocyte ring',
      'emerging gametocyte',
      'non-activated gametocyte', #a unemerged gametocyte
      'emerged gametocyte',
      'mature gametocyte',
      'female gametocyte',
      'male gametocyte',
      'emerging male gametocyte',
      'emerged male gametocyte',
      'late gametocyte',
      'early gametocyte',
      'female gamete',
      'gamete',
      'gamete formation',
      'retort',
      'oocyst protrusion', #perhaps there is a better name for this. It is like retort except it is the ookinete->oocyst, not zygote->ookinete
      'merozoite invasion', #blood stage only, not liver->blood merozoite
      'ookinete',
      'gametocyte committed early ring',
      'salivary gland sporozoite',
      'oocyst sporozoite',
      'hemocoel sporozoite',
      'oocyst',
      'early oocyst',
      'sporulating oocyst',
      'mature sporoblast',
      'ookinete retort',
      'midgut oocyst',
      'mature ookinete',
      'zygote',
      'sporozoite invasion',
      'after sporozoite invasion',
      'developing oocyst',
      'sporozoite',
      'extracellular merozoite',
      'after rupture', #after the RBC has ruptured. Not the same as free merozoite, but sort of I guess
      'invasion',
      'hepatocyte sporozoite',
      'hepatocyte',
      'early hepatocyte',
      'late hepatocyte',
      'hepatocyte schizont',
      'hepatocyte stage day 3',
      'hepatocyte stage day 5',
      'hepatocyte stage day 7',
      'hepatocyte merozoite',
      'immature oocyst from day 6 onwards',
      'several hours post invasion',
      'multiple infected erythrocyte ring',
      'double infected erythrocyte trophozoites',
      '12 hours after merozoite invasion',
      '18-36 hours after merozoite invasion',
      '24 hours after merozoite invasion',
      '30 hours after merozoite invasion',
      '40 hours after merozoite invasion',
      '48 hours after merozoite invasion',
      '11-16 days after mosquito infective blood meal',
      '60 hours after sporozoite invasion',
    ],
    Species::TOXOPLASMA_GONDII_NAME => [
      'sporozoite',
      'sporozoite invasion',
      'sporozoite 2 hours post inoculation',
      'sporozoite 6 hours post inoculation',
      'sporozoite 12 hours post inoculation',
      'sporozoite 18 hours post inoculation',
      'sporozoite parasitophorous vacuole 1',
      'merozoite',
      'mature bradyzoite',
      'bradyzoite',
      'day 4 bradyzoite',
      'intracellular bradyzoite',
      'enteric',
      'tachyzoite',
      'non-dividing tachyzoite',
      'intracellular tachyzoite until 0.5-4 hours',
      'intracellular tachyzoite after 0.5-4 hours',
      '24 hours after tachyzoite infection',
      '20 hours after tachyzoite infection',
      '16 hours after tachyzoite infection',
      'tachyzoite 24 hours after invasion',
      'extracellular tachyzoite',
      'intracellular tachyzoite',
      'early intracellular tachyzoite',
      'late intracellular tachyzoite',
      'tachyzoite schizont',
      'early multinucleate tachyzoite',
      'late multinucleate tachyzoite',
      'immature daughter tachyzoites',
      'after assembly of tachyzoite daughter cells',
      'early multinucleate tachyzoite',
      'late multinucleate tachyzoite',
      'after tachyzoite division',
      'inner membrane complex formation before arrival of IMC1',
      'tachyzoite daughter cell inner membrane complex formation',
      'tachyzoite gliding motility',
      'tachyzoite invasion',
      'after tachyzoite invasion',
      'early tachyzoite invasion',
      'tachyzoite attachment', #during invasion
      'shortly after invasion of tachyzoite',
      'mother tachyzoite',
      'mother tachyzoite mitotic division',
      'daughter tachyzoite',
      'daughter tachyzoites before acquisition of plasma membrane',
      'first division of bradyzoite',
      'macrogamete',
      'microgamete',
      'microgametocytogeny',
      'macrogametocyte',
      'proliferative microgametocyte',
      'extracellular microgamete',
      'mature microgametogeny',
      'flagellate growth',
      'tachyzoite g1 phase',
      'early tachyzoite g1 phase',
      'tachyzoite mitosis',
      'tachyzoite s-phase',
      'tachyzoite cell division',
      'mature schizont merozoite',
      'early merozoite',
      'extracellular merozoite',
      'schizont',
      'early- to mid- stage schizont',
      'multinucleate mid-stage schizont',
      'trophozoite',
    ],
    Species::BABESIA_BOVIS_NAME => [
      'merozoite',
      'merozoite invasion',
      'intracellular merozoite',
      'sporozoite'
    ],
    Species::NEOSPORA_CANINUM_NAME => [
      'tachyzoite',
      'bradyzoite'
    ],
    Species::OTHER_SPECIES => { #for unsequenced species most likely
      'Plasmodium gallinaceum' => [
        'early ring',
        'trophozoite',
        'schizont',
        'ookinete',
        'mature ookinete',
        'oocyst sporozoite',
        'salivary gland sporozoite',
      ],
      'Plasmodium malariae' => [
        'oocyst maturation',
        'sporoblast',
        'sporozoites ruptured into the midgut lumen',
        'sporozoites ruptured into midgut epithelial cells',
      ],
      'Sarcocystis neurona' => [
        'merozoite'
      ],
      'Sarcocystis muris' => [
      ],
      'Babesia divergens' => [
        'merozoite'
      ],
      'Babesia equi' => [
        'merozoite',
        'intracellular merozoite',
      ],
      'Babesia gibsoni' => [
        'oocyte',
        'intracellular merozoite',
        'early single intracellular merozoite',
        'ring intracellular merozoite',
        'extracellular merozoite',
        'merozoite',
        'ring stage of trophozoite'
      ],
      'Babesia bigemina' => [
        'merozoite'
      ],
      'Theileria lestoquardi' => [
        'macroschizont',
      ],
      'Eimeria ascervulina' => [
        'daughter cell formation',
        'macrogamete',
        'proliferative microgametocyte',
        'flagellate growth',
        'microgametogeny',
        'mature microgametogeny',
        'free microgamete',
      ],
      'Eimeria maxima' => [
        'merozoite',
        'macrogamete',
        'proliferative microgametocyte',
        'flagellate growth',
        'microgametogeny',
        'mature microgametogeny',
        'free microgamete',
      ],
      'Eimeria tenella' => [
        'sporozoite',
        'extracellular sporozoite',
        'intracellular sporozoite',
        'host cell exposed extracellular sporozoite',
        'sporozoite invasion',
        'after sporozoite invasion',
        'schizont',
        'early first generation schizont',
        'mature first generation schizont',
        'early second generation schizont',
        'mature second generation schizont',
        'developing schizont',
        'mid stage schizont',
        'enlarging schizont',
        'mature schizont',
        'daughter cell formation',
        'merozoite',
        'early merozoite',
        'first generation merozoite',
        'second generation merozoite',
        'proliferative microgametocyte',
        'flagellate growth',
        'microgametogeny',
        'mature microgametogeny',
        'free microgamete',
        'gametocyte',
        'microgamete',
        'early microgamete',
        'mature microgamete',
        'macrogamete',
        'mature macrogamete',
        'oocyst'
      ]
    },
    Species::CRYPTOSPORIDIUM_PARVUM_NAME => [
      'sporozoite',
      'extracellular sporozoite',
      'unexcysted sporozoite',
      'freshly excysted sporozoite',
      'sporozoite invasion',
      'oocyst',
      'immature oocyst',
      'empty oocyst',
      'fully sporulated oocyst',
      'intracellular meront',
      'intracellular stages',
      'merozoite containing meront',
      'meront',
      'mature type i meront',
      'merozoite',
      'type i merozoite',
      'early macrogametocyte',
      'early macrogamete',
      'late macrogamete',
      'trophozoite',
    ],
    Species::THEILERIA_ANNULATA_NAME => [
      'macroschizont',
      'schizont'
    ],
    Species::THEILERIA_PARVA_NAME => [
    ],
    Species::PLASMODIUM_BERGHEI_NAME => [
      'blood stages',
      'early blood stages',
      'ring',
      'trophozoite',
      'schizont',
      'early schizont',
      'late schizont',
      'cytomere',
      'merozoite',
      'gametocyte',
      'macrogametocyte',
      'microgametocyte',
      'activated microgametocyte',
      'macrogamete',
      'microgamete',
      'microgamete mitosis',
      'mosquito stages',
      'zygote',
      'retort',
      'early retort',
      'ookinete protrusion',
      'ookinete',
      'ookinete 20 hours after fertilization',
      'mature ookinete',
      'oocyst protrusion',
      'oocyst',
      'early oocyst',
      'late oocyst',
      'midgut oocyst',
      'sporulating oocyst',
      'mature oocyst',
      'day 5 oocyst',
      'day 15 oocyst',
      'extracellular sporozoite',
      'sporozoite',
      'oocyst sporozoite',
      'midgut sporozoite',
      'hemolymph sporozoite',
      'salivary gland sporozoite',
      'after sporozoite invasion',
      '2 hours after sporozoite invasion',
      '8 hours after sporozoite invasion',
      'hepatic',
      'early hepatic',
      'mid hepatic',
      'late hepatic',
      'late hepatic schizont',
      'terminal hepatic',
      'merozome',
      'cytomere',
      'hepatocyte merozoite',
    ],
    Species::VIVAX_NAME => [
      'ring',
      'trophozoite',
      'schizont',
      'mature schizont',
      'merozoite',
      'extracellular merozoite',
      'zygote',
      'ookinete'
    ],
    Species::YOELII_NAME => [
      'ring',
      'trophozoite',
      'early trophozoite',
      'schizont',
      'early schizont',
      'late schizont',
      'merozoite',
      'gametocyte',
      'zygote',
      'ookinete',
      '7 day old oocyst',
      'sporozoite',
      'oocyst sporozoite',
      'hemolymph sporozoite',
      'salivary gland sporozoite',
      'hepatic',
    ],
    Species::KNOWLESI_NAME => [
      'merozoite',
      'blood stages',
      'sporozoite',
    ],
    Species::CHABAUDI_NAME => [
      'blood stages',
      'intraerythrocytic',
      'maturing parasites',
      'merozoite',
    ],
  }
end
