class MicroarrayTimepoint < ActiveRecord::Base
  has_many :microarray_measurements, :dependent => :destroy
  belongs_to :microarray
  
  WINZELER_2003_EARLY_RING_SORBITOL = 'Cell Cycle 1 (Sorbitol), Early Ring'
  WINZELER_2003_LATE_RING_SORBITOL = 'Cell Cycle 1 (Sorbitol), Late Ring'
  WINZELER_2003_EARLY_TROPHOZOITE_SORBITOL = 'Cell Cycle 1 (Sorbitol), Early Trophozoite'
  WINZELER_2003_LATE_TROPHOZOITE_SORBITOL = 'Cell Cycle 1 (Sorbitol), Late Trophozoite'
  WINZELER_2003_EARLY_SCHIZONT_SORBITOL = 'Cell Cycle 1 (Sorbitol), Early Schizogony'
  WINZELER_2003_LATE_SCHIZONT_SORBITOL = 'Cell Cycle 1 (Sorbitol), Late Schizogony'
  WINZELER_2003_MEROZOITE_SORBITOL = 'Cell Cycle 1 (Sorbitol), Merozoite'
  WINZELER_2003_EARLY_RING_TEMPERATURE = 'Cell Cycle 2 (Temperature), Early Ring'
  WINZELER_2003_LATE_RING_TEMPERATURE = 'Cell Cycle 2 (Temperature), Late Ring'
  WINZELER_2003_EARLY_TROPHOZOITE_TEMPERATURE = 'Cell Cycle 2 (Temperature), Early Trophozoite'
  WINZELER_2003_LATE_TROPHOZOITE_TEMPERATURE = 'Cell Cycle 2 (Temperature), Late Trophozoite'
  WINZELER_2003_EARLY_SCHIZONT_TEMPERATURE = 'Cell Cycle 2 (Temperature), Early Schizogony'
  WINZELER_2003_LATE_SCHIZONT_TEMPERATURE = 'Cell Cycle 2 (Temperature), Late Schizogony'
  WINZELER_2003_MEROZOITE_TEMPERATURE = 'Cell Cycle 2 (Temperature), Merozoite'
  WINZELER_2003_GAMETOCYTE_TEMPERATURE = 'Gametocyte'
  WINZELER_2003_SPOROZOITE_1_TEMPERATURE = 'Sporozoite Replicate 1'
  WINZELER_2003_SPOROZOITE_2_TEMPERATURE = 'Sporozoite Replicate 2'
  
  WINZELER_RING_TIMEPOINT_NAMES = [
    WINZELER_2003_EARLY_RING_SORBITOL,
    WINZELER_2003_LATE_RING_SORBITOL,
    WINZELER_2003_EARLY_RING_TEMPERATURE,
    WINZELER_2003_LATE_RING_TEMPERATURE
  ]
  WINZELER_TROPHOZOITE_TIMEPOINT_NAMES = [
    WINZELER_2003_EARLY_TROPHOZOITE_SORBITOL,
    WINZELER_2003_LATE_TROPHOZOITE_SORBITOL,
    WINZELER_2003_EARLY_TROPHOZOITE_TEMPERATURE,
    WINZELER_2003_LATE_TROPHOZOITE_TEMPERATURE
  ]
  WINZELER_SCHIZONT_TIMEPOINT_NAMES = [
    WINZELER_2003_EARLY_SCHIZONT_SORBITOL,
    WINZELER_2003_LATE_SCHIZONT_SORBITOL,
    WINZELER_2003_EARLY_SCHIZONT_TEMPERATURE,
    WINZELER_2003_LATE_SCHIZONT_TEMPERATURE
  ]
end
